//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dog
    {
        public int? dogsID { get; set; }
        public string dogURL { get; set; }
        public string dogTitle { get; set; }
    }
}
