//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public Nullable<int> projectID { get; set; }
        public string projectTitle { get; set; }
        public string techUsed { get; set; }
        public string description { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
