//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioApi.Models
{
    using System;
    using System.Collections.Generic;
  using System.Runtime.InteropServices;

  public partial class resume
    {
        public Nullable<int> resumeID { get; set; }
        public string company { get; set; }
        public string role { get; set; }
        public string startDT { get; set; }
        public string endDT { get; set; }
        public Nullable<int> sort { get; set; }
        public string description { get; set; }
        public List<string> bullets { get; set; }
    }
}
